# Mostly based on Eric Niebler's range-v3 one
# https://github.com/Manu343726/siplasplas/blob/master/.travis.yml

language: cpp


compiler: clang

addons:
  apt:
    sources:
        - llvm-toolchain-precise
        - llvm-toolchain-precise-3.8
        - ubuntu-toolchain-r-test
    packages:
        - clang-3.8
        - g++-5

matrix:
    include:

    - env: BUILD_TYPE=Debug CLANG_VERSION=3.8 COMPILER=clang++-3.8
      os: linux
      addons: *clang37

    - env: BUILD_TYPE=Debug GCC_VERSION=5 COMPILER=g++-5
      os: linux
      addons: *gcc5

before_install:
    - git submodule update --init --recursive
    - if [ -n "$GCC_VERSION" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ -z "$GCC_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
    - which $CXX
    - which $CC
    - $CXX --version
    - $CC --version

install:
    # Install New version of cmake
    - CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
    - mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    - export PATH=${DEPS_DIR}/cmake/bin:${PATH}

    - cd ${TRAVIS_BUILD_DIR}

      # Configure and build project:
    - if [ ! -d build ]; then mkdir build; fi
    - cd build

    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build .
    - ctest -VV
