# Mostly based on Eric Niebler's range-v3 one
# https://github.com/Manu343726/siplasplas/blob/master/.travis.yml

language: cpp


compiler: clang

addons:
  apt:
    sources:
        - boost-latest
        - llvm-toolchain-precise
        - llvm-toolchain-precise-3.8
        - ubuntu-toolchain-r-test
    packages:
        - clang-3.8
        - g++-5
        - libboost1.55-all-dev
        - cmake

compiler:
    - g++


before_install:

    - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi
    - git submodule update --init --recursive

install:
      # Configure and build project:
    - if [ ! -d build ]; then mkdir build; fi
    - cd build

    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build .
    - ctest -VV
