# Mostly based on Eric Niebler's range-v3 one
# https://github.com/Manu343726/siplasplas/blob/master/.travis.yml

language: cpp


compiler: clang

addons:
  apt:
    sources:
        - boost-latest
        - llvm-toolchain-precise
        - llvm-toolchain-precise-3.8
        - ubuntu-toolchain-r-test
    packages:
        - clang-3.8
        - g++-5
        - libboost1.55-all-dev

compiler:
    - g++


before_install:

    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
    - git submodule update --init --recursive

install:

    # From: https://github.com/boostorg/hana/blob/master/.travis.yml
    ############################################################################
    # Install a recent CMake (unless already installed on OS X)
    ############################################################################
    - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
        mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      else
        if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
      fi

       # Configure and build project:
    - if [ ! -d build ]; then mkdir build; fi
    - cd build

    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build .
    - ctest -VV
