# Mostly based on Eric Niebler's range-v3 one
# https://github.com/Manu343726/siplasplas/blob/master/.travis.yml

language: cpp

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5

addons:
    apt:
        sources:
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        packages:
            - cmake
            - cmake-data

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

    - cmake --version

    - cd ${TRAVIS_BUILD_DIR}

      # Configure and build project:
    - if [ ! -d build ]; then mkdir build; fi
    - cd build

    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build .
    - ctest -VV
