# Mostly based on Eric Niebler's range-v3 one
# https://github.com/Manu343726/siplasplas/blob/master/.travis.yml

language: cpp

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5

install:
    # Install New version of cmake
    - CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz"
    - mkdir cmake && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    - export PATH=${DEPS_DIR}/cmake/bin:${PATH}

    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

    - cmake --version

    - cd ${TRAVIS_BUILD_DIR}

      # Configure and build project:
    - if [ ! -d build ]; then mkdir build; fi
    - cd build

    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build .
    - ctest -VV
